Ensure that we can generate a 6 character MFA code
With the supplied $AWS_MFA_SECRET we should be able to generate a 6 character
MFA code. If not exit and give a hint.

diff --git a/bin/configure-commands/login b/bin/configure-commands/login
--- a/bin/configure-commands/login
+++ b/bin/configure-commands/login
@@ -101,6 +101,13 @@ echo "==> Attempting MFA..."
 
 MFA_CODE="$(oathtool --base32 --totp "$AWS_MFA_SECRET")"
 
+if [ ${#MFA_CODE} -ne 6 ]
+then
+  echo "==> Failed to generate an MFA code"
+  echo "==> please see https://github.com/dxw/dalmatian-tools#why-am-i-seeing-oathtool-base32-decoding-failed-base32-string-is-invalid"
+  exit 1
+fi
+
 export AWS_ACCESS_KEY_ID
 export AWS_SECRET_ACCESS_KEY
 
