Don't write out the config file unless the login works.
If the credentials don't work there is  no point in saving them.

diff --git a/bin/configure-commands/login b/bin/configure-commands/login
--- a/bin/configure-commands/login
+++ b/bin/configure-commands/login
@@ -75,7 +75,25 @@ CONFIG_JSON_STRING=$(
 
 echo "$CONFIG_JSON_STRING" > "$DALMATIAN_CONFIG_FILE"
 
-echo "==> Storing credentials in $DALMATIAN_CREDENTIALS_FILE ..."
+
+echo "==> Attempting MFA..."
+
+MFA_CODE="$(oathtool --base32 --totp "$AWS_MFA_SECRET")"
+
+if [ ${#MFA_CODE} -ne 6 ]
+then
+  echo "==> Failed to generate an MFA code"
+  echo "==> please see https://github.com/dxw/dalmatian-tools#why-am-i-seeing-oathtool-base32-decoding-failed-base32-string-is-invalid"
+  exit 1
+fi
+
+export AWS_ACCESS_KEY_ID
+export AWS_SECRET_ACCESS_KEY
+
+if "$APP_ROOT/bin/aws/mfa" -m "$MFA_CODE"
+then
+echo "==> Login success!"
+echo "==> Storing credentials in $DALMATIAN_CREDENTIALS_FILE" 
 
 CREDENTIALS_JSON_STRING=$(
   jq -n \
@@ -96,24 +114,6 @@ echo "$CREDENTIALS_JSON_STRING" | gpg \
   -r "$GPG_ENCRYPT_EMAIL" \
   --out "$DALMATIAN_CREDENTIALS_FILE"
 chmod 600 "$DALMATIAN_CREDENTIALS_FILE"
-
-echo "==> Attempting MFA..."
-
-MFA_CODE="$(oathtool --base32 --totp "$AWS_MFA_SECRET")"
-
-if [ ${#MFA_CODE} -ne 6 ]
-then
-  echo "==> Failed to generate an MFA code"
-  echo "==> please see https://github.com/dxw/dalmatian-tools#why-am-i-seeing-oathtool-base32-decoding-failed-base32-string-is-invalid"
-  exit 1
-fi
-
-export AWS_ACCESS_KEY_ID
-export AWS_SECRET_ACCESS_KEY
-
-if "$APP_ROOT/bin/aws/mfa" -m "$MFA_CODE"
-then
-echo "==> Login success!"
 else
   echo "==> Login failed"
 fi
