(Chore) Refactor the `dalmatian` command to use `dalmatian login`
This modifies the `dalmatian` command to use the credentials generatated by `dalmatian login`, to then subsequently pass the AWS credentials onto the requested command

diff --git a/bin/dalmatian b/bin/dalmatian
--- a/bin/dalmatian
+++ b/bin/dalmatian
@@ -21,6 +21,7 @@ then
 fi
 
 APP_ROOT="$( cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd -P)"
+export APP_ROOT
 
 if [ "${1:0:1}" == "-" ]
 then
@@ -53,11 +54,30 @@ then
     do
       SUBCOMMANDS+=("$(basename "$d")")
     done
-    IFS=$'\n' SUBCOMMANDS=($(sort <<<"${SUBCOMMANDS[*]}"))
+    IFS=" " read -r -a SUBCOMMANDS <<< "$(sort <<<"${SUBCOMMANDS[*]}")"
+
+    # list configure-commands
+    FILES=()
+    while IFS=  read -r -d $'\0'; do
+      FILES+=("$REPLY")
+    done < <(find "$APP_ROOT/bin/configure-commands" -maxdepth 1 -type f -print0)
+
+    CONFIGURE_COMMANDS=()
+    for f in "${FILES[@]}"
+    do
+      CONFIGURE_COMMANDS+=("$(basename "$f")")
+    done
+    IFS=" " read -r -a CONFIGURE_COMMANDS <<< "$(sort <<<"${CONFIGURE_COMMANDS[*]}")"
+
+    for CONFIGURE_COMMAND in "${CONFIGURE_COMMANDS[@]}"
+    do
+      echo "  $CONFIGURE_COMMAND"
+    done
+    echo ""
 
     for SUBCOMMAND in "${SUBCOMMANDS[@]}"
     do
-      if [[ "$SUBCOMMAND" != "bin" && "$SUBCOMMAND" != "tmp" ]]
+      if [[ "$SUBCOMMAND" != "bin" && "$SUBCOMMAND" != "tmp" && "$SUBCOMMAND" != "configure-commands" ]]
       then
         echo "  $SUBCOMMAND"
         FILES=()
@@ -70,7 +90,7 @@ then
         do
           COMMANDS+=("$(basename "$f")")
         done
-        IFS=$'\n' COMMANDS=($(sort <<<"${COMMANDS[*]}"))
+        IFS=" " read -r -a COMMANDS <<< "$(sort <<<"${COMMANDS[*]}")"
 
         for COMMAND in "${COMMANDS[@]}"
         do
@@ -87,17 +107,144 @@ SUBCOMMAND="$1"
 COMMAND="$2"
 COMMAND_ARGS=( "${@:3}" )
 
-if [[ -z "$SUBCOMMAND" || -z "$COMMAND" ]]
+if [[ -z "$SUBCOMMAND" && -z "$COMMAND" ]]
 then
   usage
 fi
 
+if [[ -z "$COMMAND" ]]
+then
+  "$APP_ROOT/bin/configure-commands/$SUBCOMMAND"
+  exit 0
+fi
+
+DALMATIAN_CONFIG_STORE="$HOME/.config/dalmatian"
+DALMATIAN_CONFIG_FILE="$DALMATIAN_CONFIG_STORE/config.json"
+DALMATIAN_CREDENTIALS_FILE="$DALMATIAN_CONFIG_STORE/credentials.json.enc"
+DALMATIAN_MFA_CREDENTIALS_FILE="$DALMATIAN_CONFIG_STORE/mfa_credentials.json"
+DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_FILE="$DALMATIAN_CONFIG_STORE/assume_role_credentials.json"
+MFA_CONFIGURED=0
+ASSUME_MAIN_ROLE_CONFIGURED=0
+
+if [ ! -f "$DALMATIAN_CONFIG_FILE" ]
+then
+  echo "Error: You are not logged into Dalmatian"
+  echo "       Run \`dalmatian login\` to continue"
+  exit 1
+fi
+
+AWS_DEFAULT_REGION="eu-west-2" # London
+export AWS_DEFAULT_REGION
+
+DALMATIAN_CONFIG_JSON_STRING=$(cat "$DALMATIAN_CONFIG_FILE")
+ACCOUNT_ID=$(echo "$DALMATIAN_CONFIG_JSON_STRING" | jq -r '.account_id')
+DALMATIAN_ROLE=$(echo "$DALMATIAN_CONFIG_JSON_STRING" | jq -r '.dalmatian_role')
+
+# If MFA credentials exist, check if they have expired
+if [ -f "$DALMATIAN_MFA_CREDENTIALS_FILE" ]
+then
+  DALMATIAN_MFA_CREDENTIALS_JSON_STRING=$(cat "$DALMATIAN_MFA_CREDENTIALS_FILE")
+  DALMATIAN_MFA_EXPIRATION=$(echo "$DALMATIAN_MFA_CREDENTIALS_JSON_STRING" | jq -r '.aws_session_expiration')
+  DALMATIAN_MFA_EXPIRATION_SECONDS=$(date -j -f "%F T %T %z" "$DALMATIAN_MFA_EXPIRATION" +"%s")
+  EPOCH=$(date +%s)
+  if [ "$DALMATIAN_MFA_EXPIRATION_SECONDS" -lt "$EPOCH" ]
+  then
+    echo "==> MFA credentials expired, requesting new credentials ..."
+  else
+    MFA_CONFIGURED=1
+  fi
+fi
+
 if [[ "$SUBCOMMAND" == "aws" && "$COMMAND" == "mfa" ]]
 then
-  AWS_PROFILE=${AWS_PROFILE:-dalmatian}
-else
-  AWS_PROFILE=${AWS_PROFILE:-dalmatian-admin}
+  RUN_AWS_MFA=1
 fi
+
+# Update MFA credentials if needed, or if the dalmatian aws mfa command is ran
+if [[ -n "$RUN_AWS_MFA" || "$MFA_CONFIGURED" == 0 ]]
+then
+  DALMATIAN_CREDENTIALS_FILE="$DALMATIAN_CREDENTIALS_FILE.enc"
+  DALMATIAN_CREDENTIALS_JSON_STRING=$(
+    gpg --decrypt \
+      --quiet \
+      < "$DALMATIAN_CREDENTIALS_FILE"
+  )
+
+  AWS_ACCESS_KEY_ID=$(echo "$DALMATIAN_CREDENTIALS_JSON_STRING" | jq -r '.aws_access_key_id')
+  AWS_SECRET_ACCESS_KEY=$(echo "$DALMATIAN_CREDENTIALS_JSON_STRING" | jq -r '.aws_secret_access_key')
+  AWS_MFA_SECRET=$(echo "$DALMATIAN_CREDENTIALS_JSON_STRING" | jq -r '.aws_mfa_secret')
+  export AWS_ACCESS_KEY_ID
+  export AWS_SECRET_ACCESS_KEY
+  MFA_CODE="$(oathtool --base32 --totp "$AWS_MFA_SECRET")"
+  "$APP_ROOT/bin/aws/mfa" -m "$MFA_CODE"
+  if [ -n "$RUN_AWS_MFA" ]
+  then
+    exit 0
+  fi
+fi
+
+# export MFA credentials
+DALMATIAN_MFA_CREDENTIALS_JSON_STRING=$(cat "$DALMATIAN_MFA_CREDENTIALS_FILE")
+AWS_ACCESS_KEY_ID=$(echo "$DALMATIAN_MFA_CREDENTIALS_JSON_STRING" | jq -r '.aws_access_key_id')
+AWS_SECRET_ACCESS_KEY=$(echo "$DALMATIAN_MFA_CREDENTIALS_JSON_STRING" | jq -r '.aws_secret_access_key')
+AWS_SESSION_TOKEN=$(echo "$DALMATIAN_MFA_CREDENTIALS_JSON_STRING" | jq -r '.aws_session_token')
+export AWS_ACCESS_KEY_ID
+export AWS_SECRET_ACCESS_KEY
+export AWS_SESSION_TOKEN
+
+# Check if the assume role credentials have expired
+if [ -f "$DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_FILE" ]
+then
+  DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_JSON_STRING=$(cat "$DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_FILE")
+  DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_EXPIRATION=$(echo "$DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_JSON_STRING" | jq -r '.aws_session_expiration')
+  DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_EXPIRATION_SECONDS=$(date -j -f "%F T %T %z" "$DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_EXPIRATION" +"%s")
+  EPOCH=$(date +%s)
+  if [ "$DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_EXPIRATION_SECONDS" -lt "$EPOCH" ]
+  then
+    echo "==> Assume role credentials expired ..."
+  else
+    ASSUME_MAIN_ROLE_CONFIGURED=1
+  fi
+fi
+
+# Update assume role credentials if needed 
+if [ "$ASSUME_MAIN_ROLE_CONFIGURED" == "0" ]
+then
+  echo "==> Requesting Assume Role credentials ..."
+  ASSUME_ROLE_RESULT=$(
+    aws sts assume-role \
+    --role-arn "arn:aws:iam::$ACCOUNT_ID:role/$DALMATIAN_ROLE" \
+    --role-session-name dalmatian-tools
+  )
+  AWS_ACCESS_KEY_ID=$(echo "$ASSUME_ROLE_RESULT" | jq -r '.Credentials.AccessKeyId')
+  AWS_SECRET_ACCESS_KEY=$(echo "$ASSUME_ROLE_RESULT" | jq -r '.Credentials.SecretAccessKey')
+  AWS_SESSION_TOKEN=$(echo "$ASSUME_ROLE_RESULT" | jq -r '.Credentials.SessionToken')
+  AWS_SESSION_EXPIRATION=$(echo "$ASSUME_ROLE_RESULT" | jq -r '.Credentials.Expiration' | awk -F':' -v OFS=':' '{ print $1, $2, $3$4 }')
+  DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_JSON_STRING=$(
+    jq -n \
+    --arg aws_access_key_id "$AWS_ACCESS_KEY_ID" \
+    --arg aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" \
+    --arg aws_session_token "$AWS_SESSION_TOKEN" \
+    --arg aws_session_expiration "$AWS_SESSION_EXPIRATION" \
+    '{
+      aws_access_key_id: $aws_access_key_id,
+      aws_secret_access_key: $aws_secret_access_key,
+      aws_session_token: $aws_session_token,
+      aws_session_expiration: $aws_session_expiration
+    }'
+  )
+
+  echo "$DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_JSON_STRING" > "$DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_FILE"
+fi
+
+# export assume role credentials
+DALMATIAN_MFA_CREDENTIALS_JSON_STRING=$(cat "$DALMATIAN_ASSUME_MAIN_ROLE_CREDENTIALS_FILE")
+AWS_ACCESS_KEY_ID=$(echo "$DALMATIAN_MFA_CREDENTIALS_JSON_STRING" | jq -r '.aws_access_key_id')
+AWS_SECRET_ACCESS_KEY=$(echo "$DALMATIAN_MFA_CREDENTIALS_JSON_STRING" | jq -r '.aws_secret_access_key')
+AWS_SESSION_TOKEN=$(echo "$DALMATIAN_MFA_CREDENTIALS_JSON_STRING" | jq -r '.aws_session_token')
+export AWS_ACCESS_KEY_ID
+export AWS_SECRET_ACCESS_KEY
+export AWS_SESSION_TOKEN
 
 i=1
 for a in "${COMMAND_ARGS[@]}"
@@ -106,10 +253,6 @@ do
   then
     INFRASTRUCTURE_NAME="${COMMAND_ARGS[$i]}"
   fi
-  if [ "$a" == "-p" ]
-  then
-    AWS_PROFILE="${COMMAND_ARGS[$i]}"
-  fi
   i=$(( i + 1 ))
 done
 
@@ -117,7 +260,7 @@ done
 if [ -n "$INFRASTRUCTURE_NAME" ]
 then
   # shellcheck source=bin/aws/assume-infrastructure-role
-  . "$APP_ROOT/bin/aws/assume-infrastructure-role" -i "$INFRASTRUCTURE_NAME" -p "$AWS_PROFILE"
+  . "$APP_ROOT/bin/aws/assume-infrastructure-role" -i "$INFRASTRUCTURE_NAME"
 fi
 
 # Run specified command with args
