Added coloured output, improvements to usage text, and general formatting

diff --git a/bin/certificate/list b/bin/certificate/list
--- a/bin/certificate/list
+++ b/bin/certificate/list
@@ -4,22 +4,28 @@
 set -e
 set -o pipefail
 
+. "${APP_ROOT}/lib/colors.sh"
+
 usage() {
-  echo "list certificates in an infrastructure"
-  echo 'e.g dalmatian -i <infrastructure>'
-  echo "Usage: $(basename "$0") [OPTIONS]" 1>&2
-  echo "  -h                                 - help"
-  echo "  -i <infrastructure>                - infrastructure name"
-  echo "  -d <domain_name>                   - domain name (optional)"
-  echo "  -D <output_dns_validation_records> - output DNS validation records"
+  echo "Description: List certificates in an infrastructure"
+  echo
+  echo "Usage: dalmatian certificate $(basename "$0") -i <infrastructure> [options]" 1>&2
+  echo "  -h                     Get help with this command"
+  echo "  -i <infrastructure>    Name of the infrastructure you want to target"
+  echo
+  echo "Options:"
+  echo "  -d <domain_name>       Get certificates assigned only to the specified domain name"
+  echo "  -D                     Output required DNS validation records to screen"
   exit 1
 }
 
 # if there are no arguments passed exit with usage
 if [ $# -eq 0 ]
 then
- usage
- exit 0
+  fatal "Please specify a target infrastructure"
+  echo
+  usage
+  exit 0
 fi
 
 DOMAIN_NAME=""
@@ -44,11 +50,12 @@ while getopts "i:d:s:Dh" opt; do
   esac
 done
 
-if [[
-  -z "$INFRASTRUCTURE_NAME"
-]]
+if [[ -z "$INFRASTRUCTURE_NAME" ]]
 then
+  fatal "Please specify a target infrastructure"
+  echo
   usage
+  exit 0
 fi
 
 if [ -n "$DOMAIN_NAME" ]
@@ -74,6 +81,9 @@ done < <(echo "$CLOUDFRONT_CERTIFICATE_ARNS")
 
 ALL_CERTIFICATES=("${LB_CERTIFICATES[@]}" "${CLOUDFRONT_CERTIFICATES[@]}")
 
+echo
+echo "Certificates:"
+
 for cert_arn in "${ALL_CERTIFICATES[@]}"
 do
   if [[ "${cert_arn}" == "arn:aws:acm:us-east-1"* ]]
@@ -94,7 +104,7 @@ do
       then
         echo "$r" | jq -r '.Name + " " + .Type + " " + .Value'
       else
-        echo "Validation records unavailable"
+        warn "Validation records unavailable"
       fi
     done < <(echo "$CERTIFICATE" | jq -c '.Certificate | .DomainValidationOptions[].ResourceRecord')
     echo ""
diff --git a/bin/ci/deploy-build-logs b/bin/ci/deploy-build-logs
--- a/bin/ci/deploy-build-logs
+++ b/bin/ci/deploy-build-logs
@@ -4,22 +4,27 @@
 set -e
 set -o pipefail
 
+. "${APP_ROOT}/lib/colors.sh"
+
 usage() {
-  echo "Usage: $(basename "$0") [OPTIONS]" 1>&2
-  echo "  -h                       - help"
-  echo "  -I <infrastructure_name> - infrastructure name "
+  echo "Usage: dalmatian ci $(basename "$0") -i <infrastructure>" 1>&2
+  echo "  -h                   Get help with this command"
+  echo "  -i <infrastructure>  Name of the infrastructure you want to target"
   exit 1
 }
 
 # if there are no arguments passed exit with usage
-if [ $# -lt 1 ]
+if [ $# -eq 0 ]
 then
- usage
+  fatal "Please specify a target infrastructure"
+  echo
+  usage
+  exit 0
 fi
 
-while getopts "I:h" opt; do
+while getopts "i:h" opt; do
   case $opt in
-    I)
+    i)
       INFRASTRUCTURE_NAME=$OPTARG
       ;;
     h)
@@ -31,11 +36,12 @@ while getopts "I:h" opt; do
   esac
 done
 
-if [[
-  -z "$INFRASTRUCTURE_NAME"
-]]
+if [[ -z "$INFRASTRUCTURE_NAME" ]]
 then
+  fatal "Please specify a target infrastructure"
+  echo
   usage
+  exit 0
 fi
 
 PIPELINE_STATUS=$(aws codepipeline get-pipeline-state --name "ci-terraform-build-pipeline")
@@ -65,12 +71,14 @@ do
   fi
   PIPELINE_STATUS=$(aws codepipeline get-pipeline-state --name "ci-terraform-build-pipeline")
   BUILD_STATUS=$(echo "$PIPELINE_STATUS" | jq -r --arg build_name "Build-$INFRASTRUCTURE_NAME" '.stageStates[] | select(.stageName == "Build") | .actionStates[] | select(.actionName == $build_name) | .latestExecution.status')
+
+  echo
   if [ "$BUILD_STATUS" == "Failed" ]
   then
-    echo "Build Failed"
-    exit 1
+    fatal "Build status: Failed"
   fi
+
   sleep 1
 done
 
-echo "$BUILD_STATUS"
+success "Build status: $BUILD_STATUS"
diff --git a/bin/cloudfront/clear-cache b/bin/cloudfront/clear-cache
--- a/bin/cloudfront/clear-cache
+++ b/bin/cloudfront/clear-cache
@@ -4,21 +4,27 @@
 set -e
 set -o pipefail
 
+. "${APP_ROOT}/lib/colors.sh"
+
 usage() {
-  echo "Usage: $(basename "$0") [OPTIONS]" 1>&2
-  echo "  -h                     - help"
-  echo "  -i <infrastructure>    - infrastructure name"
-  echo "  -s <service_name>      - service name"
-  echo "  -e <environment>       - environment name (e.g. 'staging' or 'prod')"
-  echo "  -P <paths>             - space separated list of paths (default '/*')"
+  echo "Usage: dalmatian cloudfront $(basename "$0") -i <infrastructure> -s <service> -e <environment> [-P <paths>]" 1>&2
+  echo "  -h                     Get help with this command"
+  echo "  -i <infrastructure>    Name of the infrastructure you want to target"
+  echo "  -s <service>           Name of the service you want to target"
+  echo "  -e <environment>       Name of the environment (e.g. 'staging' or 'prod')"
+  echo
+  echo "Options:"
+  echo "  -P <paths>             Space separated list of paths (default '/*')"
   exit 1
 }
 
 # if there are no arguments passed exit with usage
 if [ $# -eq 0 ]
 then
- usage
- exit 0
+  fatal "Please specify an infrastructure, environment and service name"
+  echo
+  usage
+  exit 0
 fi
 
 PATHS="/*"
@@ -52,10 +58,13 @@ if [[
   || -z "$SERVICE_NAME"
 ]]
 then
+  fatal "Please specify an infrastructure, environment and service name"
+  echo
   usage
+  exit 0
 fi
 
-echo "==> Finding CloudFront distribution..."
+echo "Finding CloudFront distribution..."
 
 DISTRIBUTIONS=$(aws cloudfront list-distributions)
 DISTRIBUTION=$(echo "$DISTRIBUTIONS" | jq -r --arg origin "$INFRASTRUCTURE_NAME-$SERVICE_NAME-$ENVIRONMENT-default-origin" '.DistributionList.Items[] | select(.Origins.Items[].Id==$origin)')
@@ -63,7 +72,7 @@ DISTRIBUTION_ID=$(echo "$DISTRIBUTION" | jq -r '.Id')
 DISTRIBUTION_ALIAS=$(echo "$DISTRIBUTION" | jq -r '.Aliases.Items[0]')
 DISTRIBUTION_DOMAIN=$(echo "$DISTRIBUTION" | jq -r '.DomainName')
 
-echo "==> Running invalidation on distribution $DISTRIBUTION_ID ( $DISTRIBUTION_ALIAS, $DISTRIBUTION_DOMAIN ) ..."
+echo "Invalidating cache on distribution $DISTRIBUTION_ID ( $DISTRIBUTION_ALIAS, $DISTRIBUTION_DOMAIN ) ..."
 
 DISTRIBUTION_INVALIDATION=$(aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "$PATHS")
 DISTRIBUTION_INVALIDATION_ID=$(echo "$DISTRIBUTION_INVALIDATION" | jq -r '.Invalidation.Id')
diff --git a/bin/config/list-environments b/bin/config/list-environments
--- a/bin/config/list-environments
+++ b/bin/config/list-environments
@@ -1,12 +1,24 @@
 #!/bin/bash
+
+# exit on failures
+set -e
+set -o pipefail
+
 "$APP_ROOT/bin/dalmatian-refresh-config" > /dev/null
+
 usage() {
-  echo "List environment names (e.g. 'staging' or 'prod') for an infrastructure"
-  echo "Usage: $(basename "$0") <infrastructure name [OPTIONAL]>" 1>&2
-  echo "  -h                     - help"
+  echo "Description: List environment names (e.g. 'staging' or 'prod') for an infrastructure"
+  echo
+  echo "Usage: dalmatian config $(basename "$0") [infrastructure]" 1>&2
+  echo "  -h                     Get help with this command"
+  echo
+  echo "Options:"
+  echo "  [infrastructure]       Name of the infrastructure you want to target"
   exit 1
 }
+
 INFRASTRUCTURE_NAME="${1:-}"
+
 while getopts "h" opt; do
   case $opt in
     h)
diff --git a/bin/config/list-infrastructures b/bin/config/list-infrastructures
--- a/bin/config/list-infrastructures
+++ b/bin/config/list-infrastructures
@@ -1,12 +1,19 @@
 #!/bin/bash
+
+# exit on failures
+set -e
+set -o pipefail
+
 "$APP_ROOT/bin/dalmatian-refresh-config" > /dev/null
 
 usage() {
-  echo "List all infrastructures"
-  echo "Usage: $(basename "$0")" 1>&2
-  echo "  -h                     - help"
+  echo "Description: List all infrastructures"
+  echo
+  echo "Usage: dalmatian config $(basename "$0")" 1>&2
+  echo "  -h                     Get help with this command"
   exit 1
 }
+
 while getopts "h" opt; do
   case $opt in
     h)
@@ -17,4 +24,5 @@ while getopts "h" opt; do
       exit;;
   esac
 done
+
 yq e '.infrastructures | keys()' "$APP_ROOT/bin/tmp/dalmatian-config/dalmatian.yml" | sed 's/- *//g'
diff --git a/bin/dalmatian-refresh-config b/bin/dalmatian-refresh-config
--- a/bin/dalmatian-refresh-config
+++ b/bin/dalmatian-refresh-config
@@ -6,14 +6,14 @@ set -o pipefail
 
 SCRIPT_PATH="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
 
-echo "==> Finding Dalmatian config..."
+echo "Finding Dalmatian config..."
 CI_PIPELINE=$(aws codepipeline get-pipeline --name ci-terraform-build-pipeline)
 CI_BUILD_PROJECT_NAME=$(echo "$CI_PIPELINE" | jq -r '.pipeline.stages[] | select(.name == "Build") | .actions[] | select(.name == "Build-ci") | .configuration.ProjectName')
 
 BUILD_PROJECTS=$(aws codebuild batch-get-projects --names "$CI_BUILD_PROJECT_NAME")
 DALMATIAN_CONFIG_REPO=$(echo "$BUILD_PROJECTS" | jq -r '.projects[0].environment.environmentVariables[] | select(.name == "dalmatian_config_repo") | .value')
 
-echo "==> Fetching Dalmatian config..."
+echo "Fetching Dalmatian config..."
 rm -rf "$SCRIPT_PATH/tmp/dalmatian-config"
 
 set +e
@@ -22,7 +22,7 @@ set -e
 
 if [ -n "$CLONE_RESULT" ]
 then
-  echo "==> Error: Could not clone $DALMATIAN_CONFIG_REPO" 1>&2
+  fatal "Could not clone $DALMATIAN_CONFIG_REPO" 1>&2
   echo "$CLONE_RESULT" 1>&2
-  exit 1
+  exit 0
 fi
diff --git a/bin/ecs/ec2-access b/bin/ecs/ec2-access
--- a/bin/ecs/ec2-access
+++ b/bin/ecs/ec2-access
@@ -7,26 +7,32 @@
 set -e
 set -o pipefail
 
+. "${APP_ROOT}/lib/colors.sh"
+
 usage() {
-  echo "Usage: $(basename "$0") [OPTIONS]" 1>&2
-  echo "  -h                     - help"
-  echo "  -i <infrastructure>    - infrastructure name"
-  echo "  -e <environment>       - environment name (e.g. 'staging' or 'prod')"
-  echo "  -l                     - list available ec2 instance ids (optional)"
-  echo "  -I <instance_id>       - ec2 instance id (optional)"
+  echo "Usage: dalmatian ecs $(basename "$0") -i <infrastructure> -e <environment> [options]" 1>&2
+  echo "  -h                     Get help with this command"
+  echo "  -i <infrastructure>    Name of the infrastructure you want to target"
+  echo "  -e <environment>       Environment name (e.g. 'staging' or 'prod')"
+  echo
+  echo "Available options:"
+  echo "  -l                     List available EC2 instance ids"
+  echo "  -I <instance_id>       Target a specific EC2 instance"
   exit 1
 }
 
 # if there are no arguments passed exit with usage
 if [ $# -eq 0 ]
 then
- usage
- exit 0
+  fatal "Please specify a target infrastructure and environment"
+  echo
+  usage
+  exit 0
 fi
 
 if ! command -v session-manager-plugin > /dev/null
 then
-  echo "This script requires the \`session-manager-plugin\` to be installed:"
+  fatal "This script requires the \`session-manager-plugin\` to be installed:"
   echo "https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html"
   echo
   read -p "Enter Y to install now or anything else to exit: " SM_PLUGIN_DEP
@@ -96,10 +102,10 @@ else
   INSTANCE_NAME=$(echo "$INSTANCES" | jq -r --arg i "$INSTANCE_ID" '.Reservations[].Instances[] | select(.InstanceId == $i) | .Tags[] | select(.Key == "Name") | .Value')
   if [ -z "$INSTANCE_NAME" ];
   then
-    echo "Error: Instance ID $INSTANCE_ID not found"
+    fatal "Instance ID $INSTANCE_ID not found"
     echo "Available isntances:"
     echo "$AVAILABLE_INSTANCES"
-    exit 1
+    exit 0
   fi
 fi
 
diff --git a/bin/rds/get-root-password b/bin/rds/get-root-password
--- a/bin/rds/get-root-password
+++ b/bin/rds/get-root-password
@@ -4,19 +4,23 @@
 set -e
 set -o pipefail
 
+. "${APP_ROOT}/lib/colors.sh"
+
 usage() {
-  echo "Usage: dalmatian $(basename "$(dirname "${BASH_SOURCE[0]}")") $(basename "$0") [OPTIONS]" 1>&2
-  echo "  -h                     - help"
-  echo "  -i <infrastructure>    - infrastructure name"
-  echo "  -r <rds_name>          - RDS name (as defined in the Dalmatian config)"
-  echo "  -e <environment>       - environment name (e.g. 'staging' or 'prod')"
+  echo "Description: Get the root user password for the specified RDS"
+  echo
+  echo "Usage: dalmatian rds $(basename "$0") -i <infrastructure> -e <environment> -r <rds>" 1>&2
+  echo "  -h                     Get help with this command"
+  echo "  -i <infrastructure>    Name of the infrastructure you want to target"
+  echo "  -e <environment>       Environment name (e.g. 'staging' or 'prod')"
+  echo "  -r <rds>               RDS name (as defined in the Dalmatian config)"
   exit 1
 }
 
 # if there are no arguments passed exit with usage
 if [ $# -lt 1 ];
 then
- usage
+  usage
 fi
 
 while getopts "i:e:r:h" opt; do
@@ -44,7 +48,10 @@ if [[
   || -z "$RDS_NAME"
   || -z "$ENVIRONMENT"
 ]]; then
+  fatal "Please specify all of the required parameters"
+  echo
   usage
+  exit 0
 fi
 
 # Remove dashes from the variables to create the RDS identifier, because dashes
@@ -52,7 +59,7 @@ fi
 # need to remove them here to get the correct identifier.
 RDS_IDENTIFIER="${INFRASTRUCTURE_NAME//-/}${RDS_NAME//-/}${ENVIRONMENT//-/}"
 
-echo "==> Retrieving RDS root password from Parameter Store..."
+echo "Retrieving RDS root password from Parameter Store..."
 
 RDS_ROOT_PASSWORD_PARAMETER=$(
   aws ssm get-parameters \
@@ -64,7 +71,7 @@ RDS_ROOT_PASSWORD=$(
     | jq -r .Parameters[0].Value
 )
 
-echo "==> Getting RDS info..."
+echo "Getting RDS info..."
 
 RDS_INFO=$(
   aws rds describe-db-instances \
@@ -72,5 +79,7 @@ RDS_INFO=$(
 )
 RDS_ROOT_USERNAME=$(echo "$RDS_INFO" | jq -r .DBInstances[0].MasterUsername)
 
-echo "Root username: $RDS_ROOT_USERNAME"
-echo "Root password: $RDS_ROOT_PASSWORD"
+echo
+success "Credentials for $RDS_IDENTIFIER:"
+echo "Username: $RDS_ROOT_USERNAME"
+echo "Password: $RDS_ROOT_PASSWORD"
diff --git a/bin/rds/list-databases b/bin/rds/list-databases
--- a/bin/rds/list-databases
+++ b/bin/rds/list-databases
@@ -4,19 +4,26 @@
 set -e
 set -o pipefail
 
+. "${APP_ROOT}/lib/colors.sh"
+
 usage() {
-  echo "Usage: $(basename "$0") [OPTIONS]" 1>&2
-  echo "  -h                     - help"
-  echo "  -i <infrastructure>    - infrastructure name"
-  echo "  -r <rds_name>          - RDS name (as defined in the Dalmatian config)"
-  echo "  -e <environment>       - environment name (e.g. 'staging' or 'prod')"
+  echo "Description: List all databases on a target RDS"
+  echo
+  echo "Usage: dalmatian rds $(basename "$0") -i <infrastructure> -e <environment> -r <rds>" 1>&2
+  echo "  -h                     Get help with this command"
+  echo "  -i <infrastructure>    Name of the infrastructure you want to target"
+  echo "  -e <environment>       Environment name (e.g. 'staging' or 'prod')"
+  echo "  -r <rds>               RDS name (as defined in the Dalmatian config)"
   exit 1
 }
 
 # if there are no arguments passed exit with usage
 if [ $# -lt 1 ]
 then
- usage
+  fatal "Please populate all required parameters"
+  echo
+  usage
+  exit 0
 fi
 
 while getopts "i:e:r:h" opt; do
@@ -45,7 +52,10 @@ if [[
   || -z "$RDS_NAME"
 ]]
 then
+  fatal "Please specify an infrastructure, environment and RDS name"
+  echo
   usage
+  exit 0
 fi
 
 # Remove dashes from the variables to create the RDS identifier, because dashes
@@ -53,7 +63,7 @@ fi
 # need to remove them here to get the correct identifier.
 RDS_IDENTIFIER="${INFRASTRUCTURE_NAME//-/}${RDS_NAME//-/}${ENVIRONMENT//-/}"
 
-echo "==> Retrieving RDS root password from Parameter Store..."
+echo "Retrieving RDS root password from Parameter Store..."
 
 RDS_ROOT_PASSWORD_PARAMETER=$(
   aws ssm get-parameters \
@@ -65,7 +75,7 @@ RDS_ROOT_PASSWORD=$(
     | jq -r .Parameters[0].Value
 )
 
-echo "==> Getting RDS info..."
+echo "Getting RDS info..."
 
 RDS_INFO=$(
   aws rds describe-db-instances \
@@ -73,7 +83,7 @@ RDS_INFO=$(
 )
 RDS_VPC=$(echo "$RDS_INFO" | jq -r .DBInstances[0].DBSubnetGroup.VpcId)
 
-echo "==> Finding ECS instance..."
+echo "Finding ECS instance..."
 
 ECS_INSTANCES=$(
   aws ec2 describe-instances \
@@ -84,13 +94,11 @@ ECS_INSTANCE_ID=$(
     | jq -r .Reservations[0].Instances[0].InstanceId
 )
 
-echo "ECS instance ID: $ECS_INSTANCE_ID"
+success "Using EC2 instance ID: $ECS_INSTANCE_ID"
 
-echo "==> Listing databases..."
+echo "Listing databases..."
 
 aws ssm start-session \
   --target "$ECS_INSTANCE_ID" \
   --document-name "$RDS_IDENTIFIER-rds-db-list" \
   --parameters "RootPassword=$RDS_ROOT_PASSWORD"
-
-echo "Success!"
diff --git a/bin/rds/list-instances b/bin/rds/list-instances
--- a/bin/rds/list-instances
+++ b/bin/rds/list-instances
@@ -4,18 +4,25 @@
 set -e
 set -o pipefail
 
+. "${APP_ROOT}/lib/colors.sh"
+
 usage() {
-  echo "Usage: $(basename "$0") [OPTIONS]" 1>&2
-  echo "  -h                     - help"
-  echo "  -e <environment>       - environment (eg. 'staging' or 'prod')"
-  echo "  -i <infrastructure>    - infrastructure name"
+  echo "Description: List all RDS instances for a target infrastructure"
+  echo
+  echo "Usage: dalmatian rds $(basename "$0") -i <infrastructure> -e <environment> -r <rds>" 1>&2
+  echo "  -h                     Get help with this command"
+  echo "  -i <infrastructure>    Name of the infrastructure you want to target"
+  echo "  -e <environment>       Environment name (e.g. 'staging' or 'prod')"
   exit 1
 }
 
 # if there are no arguments passed exit with usage
 if [ $# -lt 1 ]
 then
- usage
+  fatal "Please populate all required parameters"
+  echo
+  usage
+  exit 0
 fi
 
 while getopts "i:e:h" opt; do
@@ -40,10 +47,13 @@ if [[
   -z "$ENVIRONMENT"
 ]]
 then
+  fatal "Please specify a target infrastructure and environment"
+  echo
   usage
+  exit 0
 fi
 
-echo "==> Getting RDS instances in $INFRASTRUCTURE_NAME $ENVIRONMENT..."
+echo "Listing RDS instances in $INFRASTRUCTURE_NAME for environment $ENVIRONMENT..."
 
 RDS_IDENTIFIER_SEARCH="${INFRASTRUCTURE_NAME//-/}.*${ENVIRONMENT//-/}"
 
diff --git a/bin/rds/set-root-password b/bin/rds/set-root-password
--- a/bin/rds/set-root-password
+++ b/bin/rds/set-root-password
@@ -4,23 +4,29 @@
 set -e
 set -o pipefail
 
+. "${APP_ROOT}/lib/colors.sh"
+
 usage() {
-  echo "Usage: dalmatian $(basename "$(dirname "${BASH_SOURCE[0]}")") $(basename "$0") [OPTIONS]" 1>&2
-  echo "  -h                     - help"
-  echo "  -i <infrastructure>    - infrastructure name"
-  echo "  -r <rds_name>          - RDS name (as defined in the Dalmatian config)"
-  echo "  -e <environment>       - environment name (e.g. 'staging' or 'prod')"
-  echo "  -P <new_password>      - new password to set"
+  echo "Description: Set a new root user password for the RDS"
+  echo
+  echo "Usage: dalmatian rds $(basename "$0") -i <infrastructure> -e <environment> -r <rds>" 1>&2
+  echo "  -h                     Get help with this command"
+  echo "  -i <infrastructure>    Name of the infrastructure you want to target"
+  echo "  -e <environment>       Environment name (e.g. 'staging' or 'prod')"
+  echo "  -r <rds>               RDS name (as defined in the Dalmatian config)"
   exit 1
 }
 
 # if there are no arguments passed exit with usage
 if [ $# -lt 1 ];
 then
- usage
+  fatal "Please populate all required parameters"
+  echo
+  usage
+  exit 0
 fi
 
-while getopts "i:e:r:P:h" opt; do
+while getopts "i:e:r:h" opt; do
   case $opt in
     i)
       INFRASTRUCTURE_NAME=$OPTARG
@@ -30,9 +36,6 @@ while getopts "i:e:r:P:h" opt; do
       ;;
     r)
       RDS_NAME=$OPTARG
-      ;;
-    P)
-      NEW_PASSWORD=$OPTARG
       ;;
     h)
       usage
@@ -47,9 +50,11 @@ if [[
   -z "$INFRASTRUCTURE_NAME"
   || -z "$RDS_NAME"
   || -z "$ENVIRONMENT"
-  || -z "$NEW_PASSWORD"
 ]]; then
+  fatal "Please specify a target infrastructure, environment and RDS"
+  echo
   usage
+  exit 0
 fi
 
 # Remove dashes from the variables to create the RDS identifier, because dashes
@@ -57,7 +62,7 @@ fi
 # need to remove them here to get the correct identifier.
 RDS_IDENTIFIER="${INFRASTRUCTURE_NAME//-/}${RDS_NAME//-/}${ENVIRONMENT//-/}"
 
-echo "==> Setting RDS root password in Parameter Store..."
+echo "Setting RDS root password in Parameter Store..."
 
 aws ssm put-parameter \
    --name "/$INFRASTRUCTURE_NAME/$RDS_IDENTIFIER-rds/password" \
@@ -66,7 +71,8 @@ aws ssm put-parameter \
    --key-id "alias/$INFRASTRUCTURE_NAME-$RDS_NAME-rds-$ENVIRONMENT-rds-values-ssm" \
    --overwrite
 
-echo "==> Parameter store value set"
-echo "==> For this change to take effect, run the following from dalmatian core to deploy:"
+success "Parameter store value set"
+echo
+warn "For this change to take effect, run the following from dalmatian core to deploy:"
 echo ""
 echo "    ./scripts/bin/deploy -i $INFRASTRUCTURE_NAME -e $ENVIRONMENT -S hosted-zone,vpn-customer-gateway,ecs,ecs-services,elasticache-cluster,shared-loadbalancer,waf"
diff --git a/bin/rds/shell b/bin/rds/shell
--- a/bin/rds/shell
+++ b/bin/rds/shell
@@ -4,20 +4,29 @@
 set -e
 set -o pipefail
 
+. "${APP_ROOT}/lib/colors.sh"
+
 usage() {
-  echo "Usage: dalmatian $(basename "$(dirname "${BASH_SOURCE[0]}")") $(basename "$0") [OPTIONS]" 1>&2
-  echo "  -h                     - help"
-  echo "  -i <infrastructure>    - infrastructure name"
-  echo "  -r <rds_name>          - RDS name (as defined in the Dalmatian config)"
-  echo "  -e <environment>       - environment name (e.g. 'staging' or 'prod')"
-  echo "  -I <ecs_insatnce_id>   - ECS instance ID to connect through (optional)"
+  echo "Description: Start an interactive shell on the target RDS"
+  echo
+  echo "Usage: dalmatian rds $(basename "$0") -i <infrastructure> -e <environment> -r <rds> [-I <instance_id>]" 1>&2
+  echo "  -h                     Get help with this command"
+  echo "  -i <infrastructure>    Name of the infrastructure you want to target"
+  echo "  -e <environment>       Environment name (e.g. 'staging' or 'prod')"
+  echo "  -r <rds>               RDS name (as defined in the Dalmatian config)"
+  echo
+  echo "Options:"
+  echo "  -I <instance_id>       EC2 instance ID to connect through"
   exit 1
 }
 
 # if there are no arguments passed exit with usage
 if [ $# -lt 1 ];
 then
- usage
+  fatal "Please populate all required parameters"
+  echo
+  usage
+  exit 0
 fi
 
 while getopts "i:e:r:I:h" opt; do
@@ -48,7 +57,10 @@ if [[
   || -z "$RDS_NAME"
   || -z "$ENVIRONMENT"
 ]]; then
+  fatal "Please specify a target infrastructure, environment and RDS"
+  echo
   usage
+  exit 0
 fi
 
 # Remove dashes from the variables to create the RDS identifier, because dashes
@@ -56,7 +68,7 @@ fi
 # need to remove them here to get the correct identifier.
 RDS_IDENTIFIER="${INFRASTRUCTURE_NAME//-/}${RDS_NAME//-/}${ENVIRONMENT//-/}"
 
-echo "==> Retrieving RDS root password from Parameter Store..."
+echo "Retrieving RDS root password from Parameter Store..."
 
 RDS_ROOT_PASSWORD_PARAMETER=$(
   aws ssm get-parameters \
@@ -68,7 +80,7 @@ RDS_ROOT_PASSWORD=$(
     | jq -r .Parameters[0].Value
 )
 
-echo "==> Getting RDS info..."
+echo "Getting RDS info..."
 
 RDS_INFO=$(
   aws rds describe-db-instances \
@@ -84,7 +96,7 @@ echo "VPC ID: $RDS_VPC"
 
 if [ -z "$ECS_INSTANCE_ID" ]
 then
-  echo "==> Finding ECS instance..."
+  echo "Finding ECS instance..."
 
   ECS_INSTANCES=$(
     aws ec2 describe-instances \
@@ -96,9 +108,9 @@ then
   )
 fi
 
-echo "ECS instance ID: $ECS_INSTANCE_ID"
+success "Using EC2 instance ID: $ECS_INSTANCE_ID"
 
-echo "==> Starting $RDS_ENGINE session on $RDS_IDENTIFIER..."
+echo "Starting $RDS_ENGINE session on $RDS_IDENTIFIER..."
 
 aws ssm start-session \
   --target "$ECS_INSTANCE_ID" \
